# Application Configuration
spring.application.name=newFlightBooking
server.port=9595

# Reactive MongoDB Connection
spring.data.mongodb.uri=mongodb://localhost:27017/flightdb

# JWT Configuration (ADDED)
jwt.secret=mySecretKeyForFlightBookingJWTTokenGenerationPleaseChangeThisInProductionMakeSureItsLongEnough123456
jwt.expiration=86400000

# Logging Configuration
logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG


spring.jackson.serialization.indent-output=true