spring.application.name=newFlightBooking
server.port=9595

# Reactive MongoDB connection
spring.data.mongodb.uri=mongodb://localhost:27017/flightdb

# Optional: show Mongo queries in logs
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
